## Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
dist: bionic
os:
  - linux
  - osx
julia:
  - 1.3
  - 1.4
  - nightly
matrix:
  exclude:
  - julia: 1.4
    os: osx
  - julia: nightly
    os: osx
  allow_failures:
  - julia: nightly
notifications:
  email: false
#FIXME: add registry for testing, remove afterwards
before_script:
  - julia -e 'using Pkg; pkg"registry add https://github.com/JuliaRegistries/General";'
  - julia -e 'using Pkg; pkg"registry add https://github.com/oscar-system/OscarRegistry";'
codecov: true
env:
  global:
    - OMP_NUM_THREADS=1
