name: Run tests

on:
   push:
     branches:
       - master
   pull_request:
     branches:
       - master

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        julia-version: ['1.3', '1.4', 'nightly']
        os: [ubuntu-latest, macOS-latest]
        xcode: [ '11.4', '11.3.1' ]
        cxxwrap: [ '0.9', '0.10' ]
        exclude:
        # only julia 1.4 on macOS
        # choose one arbitrary xcode version for linux
        # cxxwrap 0.9 only with 1.4
          - os: macos-latest
            julia-version: 'nightly'
          - os: macos-latest
            julia-version: '1.3'
          - os: ubuntu-latest
            xcode: '11.3.1'
          - julia-version: '1.3'
            cxxwrap: '0.9'
          - julia-version: 'nightly'
            cxxwrap: '0.9'

      fail-fast: false

    steps:
      - uses: actions/checkout@v1.0.0
      - name: "Set up Julia"
        uses: julia-actions/setup-julia@v1
        with:
          version: ${{ matrix.julia-version }}
      - name: "Pin CxxWrap"
        run: julia --project -e 'using Pkg; pkg"add CxxWrap@${{ matrix.cxxwrap }}"; pkg"pin CxxWrap";'
      - uses: julia-actions/julia-buildpkg@latest
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - uses: julia-actions/julia-runtest@latest
        env:
          DEVELOPER_DIR: /Applications/Xcode_${{ matrix.xcode }}.app/Contents/Developer
      - uses: julia-actions/julia-uploadcodecov@latest
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
